// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDk73DYLMbNIXufrCGYpOhiCk8ga7H6nw',
    appId: '1:784989018626:web:8e0d08dccea0d4fed8a51b',
    messagingSenderId: '784989018626',
    projectId: 'blogapp-e5659',
    authDomain: 'blogapp-e5659.firebaseapp.com',
    storageBucket: 'blogapp-e5659.firebasestorage.app',
    measurementId: 'G-950QKQXC5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVFVWvWig-PAxP6FNCEoOjBuonh31bx9g',
    appId: '1:784989018626:android:e3a55de94b767ce4d8a51b',
    messagingSenderId: '784989018626',
    projectId: 'blogapp-e5659',
    storageBucket: 'blogapp-e5659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1zkVo02JqhjBneOQDSV8_1_OliBeHDrE',
    appId: '1:784989018626:ios:dd372933f667b09cd8a51b',
    messagingSenderId: '784989018626',
    projectId: 'blogapp-e5659',
    storageBucket: 'blogapp-e5659.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1zkVo02JqhjBneOQDSV8_1_OliBeHDrE',
    appId: '1:784989018626:ios:dd372933f667b09cd8a51b',
    messagingSenderId: '784989018626',
    projectId: 'blogapp-e5659',
    storageBucket: 'blogapp-e5659.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDk73DYLMbNIXufrCGYpOhiCk8ga7H6nw',
    appId: '1:784989018626:web:1194b395d9fff519d8a51b',
    messagingSenderId: '784989018626',
    projectId: 'blogapp-e5659',
    authDomain: 'blogapp-e5659.firebaseapp.com',
    storageBucket: 'blogapp-e5659.firebasestorage.app',
    measurementId: 'G-SZTJPB5TZT',
  );
}
